/*
 * THIS IS A GENERATED FILE - CHANGES WILL BE OVERWRITTEN.
 */

#ifndef GENERATEDHEADERS_ODVDSCALEDCARSDATAMODEL_H
#define GENERATEDHEADERS_ODVDSCALEDCARSDATAMODEL_H

#include "odvdscaledcarsdatamodel/generated/chalmersrevere/scaledcars/ExampleMessage.h"

#endif //GENERATEDHEADERS_ODVDSCALEDCARSDATAMODEL_H
