# ODVDScaledCarsDataModel - Data structure library generated by DataStructureGenerator.
###########################################################################
# Try to find ODVDScaledCarsDataModel library.
# The user can specify an additional search path using the CMake variable
# ODVDSCALEDCARSDATAMODEL_DIR
# First, search at the specific user path setting.
IF(NOT ("${ODVDSCALEDCARSDATAMODEL_DIR}" STREQUAL ""))
    FIND_PATH(ODVDSCALEDCARSDATAMODEL_INCLUDE_DIR odvdscaledcarsdatamodel/GeneratedHeaders_ODVDScaledCarsDataModel.h
                 NAMES odvdscaledcarsdatamodel
                 PATHS ${ODVDSCALEDCARSDATAMODEL_DIR}/include
                 NO_DEFAULT_PATH)
    FIND_LIBRARY(ODVDSCALEDCARSDATAMODEL_LIBRARY
                 NAMES odvdscaledcarsdatamodel odvdscaledcarsdatamodel-static
                 PATHS ${ODVDSCALEDCARSDATAMODEL_DIR}/lib
                 NO_DEFAULT_PATH)
ENDIF()
IF(   ("${ODVDSCALEDCARSDATAMODEL_INCLUDE_DIR}" STREQUAL "ODVDSCALEDCARSDATAMODEL_INCLUDE_DIR-NOTFOUND")
   OR ("${ODVDSCALEDCARSDATAMODEL_DIR}" STREQUAL "") )
    MESSAGE(STATUS "Trying to find ODVDScaledCarsDataModel in default paths.")
    # If not found, use the system's search paths.
    FIND_PATH(ODVDSCALEDCARSDATAMODEL_INCLUDE_DIR odvdscaledcarsdatamodel/GeneratedHeaders_ODVDScaledCarsDataModel.h
                 NAMES odvdscaledcarsdatamodel
                 PATHS /usr/include
                       /usr/local/include)
    FIND_LIBRARY(ODVDSCALEDCARSDATAMODEL_LIBRARY
                 NAMES odvdscaledcarsdatamodel odvdscaledcarsdatamodel-static
                 PATHS /usr/lib
                       /usr/lib64
                       /usr/local/lib
                       /usr/local/lib64)
ENDIF()
IF("${ODVDSCALEDCARSDATAMODEL_INCLUDE_DIR}" STREQUAL "")
    MESSAGE(FATAL_ERROR "Could not find ODVDScaledCarsDataModel library.")
ENDIF()
###########################################################################
# Set linking libraries.
SET(ODVDSCALEDCARSDATAMODEL_LIBRARIES ${ODVDSCALEDCARSDATAMODEL_LIBRARY})
SET(ODVDSCALEDCARSDATAMODEL_INCLUDE_DIRS ${ODVDSCALEDCARSDATAMODEL_INCLUDE_DIR})
###########################################################################
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibODVDScaledCarsDataModel DEFAULT_MSG
                                  ODVDSCALEDCARSDATAMODEL_LIBRARY ODVDSCALEDCARSDATAMODEL_INCLUDE_DIR)
MARK_AS_ADVANCED(ODVDSCALEDCARSDATAMODEL_INCLUDE_DIR ODVDSCALEDCARSDATAMODEL_LIBRARY)
